[package]
name = "namespaces-in-operation"
version = "0.1.0"
authors = ["Carlos Valiente <carlos@pepelabs.net>"]
edition = "2021"

[dependencies]
caps = "0.3.4"
clap = "2.33.0"
libc = "0.2.68"
nix = "0.17.0"
wordexp = "0.1.0"
